Enhanced logging mechanism
RedHatInsights/yuptoo pull request #11
Opened 2022-05-26 07:38 UTC by patilsuraj767

- Shorter log statements
- Strict use of f strings instead of old string formater
- Having separate logging module will also help in cloudwatch and kibana integration.

Sequential and easy to understand log statments.
```
MainThread INFO __main__ - Started listening on kafka topic - platform.upload.qpc.
MainThread INFO __main__ - Received record on platform.upload.qpc topic for account sysaccount.
MainThread INFO yuptoo.processor.report_processor - Downloading Report from http://minio:9000/insights-upload-perma/b6230fd0ea79/WCwSwTFbZy-000017?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=BQA2GEXO711FVBVXDWKM%2F20220526%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20220526T072619Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-Amz-Signature=e8280f03693ae83bf643242cb8fbfb0e2855267ef007d3684158647b5870eb03 for account=sysaccount org_id=3340851 and request_id=b6230fd0ea79/WCwSwTFbZy-000017.
MainThread INFO yuptoo.processor.report_processor - Successfully downloaded TAR from http://minio:9000/insights-upload-perma/b6230fd0ea79/WCwSwTFbZy-000017?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=BQA2GEXO711FVBVXDWKM%2F20220526%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20220526T072619Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-Amz-Signature=e8280f03693ae83bf643242cb8fbfb0e2855267ef007d3684158647b5870eb03 for account=sysaccount org_id=3340851 and request_id=b6230fd0ea79/WCwSwTFbZy-000017.
MainThread INFO yuptoo.processor.report_processor - Attempting to decode the file ./metadata.json for account=sysaccount org_id=3340851 and request_id=b6230fd0ea79/WCwSwTFbZy-000017.
MainThread INFO yuptoo.processor.report_processor - Successfully decoded the file ./metadata.json for account=sysaccount org_id=3340851 and request_id=b6230fd0ea79/WCwSwTFbZy-000017.
MainThread INFO yuptoo.processor.report_processor - The following source metadata was uploaded: {'foreman_rh_cloud_version': '3.0.14'} for account=sysaccount org_id=3340851 and request_id=b6230fd0ea79/WCwSwTFbZy-000017.
MainThread INFO yuptoo.processor.report_processor - Attempting to decode the file ./fc90230f-617b-493d-abf9-048391a9d989.json for account=sysaccount org_id=3340851 and request_id=b6230fd0ea79/WCwSwTFbZy-000017.
MainThread INFO yuptoo.processor.report_processor - Successfully decoded the file ./fc90230f-617b-493d-abf9-048391a9d989.json for account=sysaccount org_id=3340851 and request_id=b6230fd0ea79/WCwSwTFbZy-000017.
MainThread INFO yuptoo.processor.report_processor - Processing hosts in slice with id - fc90230f-617b-493d-abf9-048391a9d989 for account=sysaccount org_id=3340851 and request_id=b6230fd0ea79/WCwSwTFbZy-000017.
MainThread INFO yuptoo.processor.report_processor - Transformed details host with id 994d9365-0e04-4dcc-bfa9-d6dc33d932ab modified: facts,transformed mac_addresses to store unique values,os_kernel_version from '4.18.0-240.el8.x86_64' to '4.18.0',os_release from 'Red Hat Enterprise Linux 8.3 (Ootpa)' to '8.3' for account=sysaccount org_id=3340851 and request_id=b6230fd0ea79/WCwSwTFbZy-000017.
MainThread INFO yuptoo.processor.report_processor - 1/1 hosts are valid for account=sysaccount org_id=3340851 and request_id=b6230fd0ea79/WCwSwTFbZy-000017.
MainThread INFO yuptoo.processor.report_processor - 1/1 hosts has been send to the inventory service for account=sysaccount org_id=3340851 and request_id=b6230fd0ea79/WCwSwTFbZy-000017.
```

2022-05-27 09:37 UTC, r14chandra approved these changes
Looks great! 👍🏻

2022-05-31 08:58 UTC, kgaikwad requested changes

2022-05-31 08:58 UTC, kgaikwad commented on yuptoo/lib/config.py
> +LOG = logging.getLogger(__name__)
Where it is being used?

2022-05-31 09:10 UTC, patilsuraj767 commented on yuptoo/lib/config.py
> +LOG = logging.getLogger(__name__)
Not used, I will remove it.

2022-05-31 09:12 UTC, patilsuraj767 commented on yuptoo/lib/config.py
> +LOG = logging.getLogger(__name__)
It is used on line 9

2022-06-02 09:57 UTC, kgaikwad requested changes
Added few minor comments. Could you also check log sentences as period is missing at the end?

2022-06-02 09:57 UTC, kgaikwad commented on yuptoo/lib/logger.py
> +    around the request_id for each log message
```suggestion
    This filter gets the request_id and tenant info from the message and adds to
    each log record. This way, every time it won't require to retrieve these details
    per log message.
```

2022-06-03 14:06 UTC, kgaikwad approved these changes
@patilsuraj767 - Added a query regarding cloudwatch config and suggestions related to it.
Noticed it now, please let me know your thoughts.

@r14chandra  - do you have any additional comments?

2022-06-03 14:06 UTC, kgaikwad commented on yuptoo/lib/logger.py
> +def clowder_config():
```suggestion

# Returns Cloudwatch config values 
def cloudwatch_config_values():
```

2022-06-07 10:57 UTC, merged