Switch to UBI8-minimal base image
RedHatInsights/yuptoo pull request #52
Opened 2023-01-24 18:27 UTC by dkuc

2023-01-25 09:52 UTC, kgaikwad requested changes
Thank you @dkuc! 
Added a small query otherwise LGTM :+1:

2023-01-25 14:59 UTC, dkuc commented on Dockerfile
> +FROM registry.access.redhat.com/ubi8/ubi-minimal:latest
Not mandatory.  Feel free to change. This whole PR should just be taken as a suggestion.

2023-01-30 08:42 UTC, patilsuraj767 commented
/retest

2023-01-30 08:57 UTC, patilsuraj767 approved these changes
LGTM :+1:  I did a quick test in EE with the PR image. Everything looks good.

2023-01-30 12:55 UTC, kgaikwad approved these changes

2023-01-30 12:57 UTC, merged

2023-01-30 12:57 UTC, kgaikwad commented
Thank you @dkuc!