RHINENG-5922 support multiple kafka brokers
RedHatInsights/yuptoo pull request #69
Opened 2023-12-15 07:33 UTC by r14chandra

2024-01-02 14:35 UTC, kgaikwad requested changes
@r14chandra , just a small suggestion added on PR. 
As it includes multiple constant variables when it comes to local development. Could you update it?

2024-01-02 14:35 UTC, kgaikwad commented on yuptoo/lib/config.py
> +    INSIGHTS_KAFKA_ADDRESS = KafkaServers
Also, handles it in `else` loop.

2024-01-03 06:55 UTC, r14chandra commented on yuptoo/lib/config.py
> +    INSIGHTS_KAFKA_ADDRESS = KafkaServers
done.

2024-01-03 09:54 UTC, kgaikwad approved these changes
LGTM :+1:  Thank you @r14chandra! Merging it.

2024-01-03 09:55 UTC, merged